<div class="container">
    <form class="form-signin" role="form"  method="post" action="/auth/forgot-password">
        <h2 class="form-signin-heading">Forgot Password</h2>
        <input type="text" class="form-control" name="email" placeholder="Email address" required autofocus>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
        <?php if($this->success) { ?>
        <div class="alert alert-success">
            Email Sent!
        </div>
        <?php } else if($this->message) { ?>
        <div class="alert alert-danger">
            <?= $this->message ?>
        </div>
        <?php } ?>
    </form>
</div>