<div class="container">
    <form class="form-signin" role="form"  method="post" action="/auth/reset-password">
        <h2 class="form-signin-heading">Reset Password</h2>
        <input type="hidden" class="form-control" name="email" value="<?= $this->email; ?>">
        <input type="hidden" class="form-control" name="token" value="<?= $this->token; ?>">
        <input type="password" class="form-control" name="password" placeholder="New Password" required autofocus>
        <input type="password" class="form-control" name="repeatPassword" placeholder="Repeat Password" required autofocus>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
        <?php if($this->success) { ?>
        <div class="alert alert-success">
            <p>Password Updated!</p>
            <p><a href="/auth/login">Log In Now</a></p>
        </div>
        <?php } else if($this->message) { ?>
        <div class="alert alert-danger">
            <?= $this->message ?>
        </div>
        <?php } ?>
    </form>
</div>