<div class="row">
    <div class="col-md-4">
        <ul class="nav nav-pills" id="item-tabs">
            <li class="active"><a href="#types">Types</a></li>
            <li><a href="#attributes">Attributes</a></li>
            <li><a href="#locations">Locations</a></li>
        </ul>
    </div>
    <div class="col-md-8 filters">
        <a href="#" class="btn btn-primary pull-right" id="add-item-type"><span class="glyphicon glyphicon-plus"></span></a>
    </div>
</div>
<div class="tab-content">
    <div class="tab-pane active" id="types">
        <br />
        <table class="types table table-responseive table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
    <div class="tab-pane" id="attributes">
        <br />
        <div class="row">
            <div class="col-md-3">
                <form>
                    <select class="form-control" id="item-type-search"></select>
                </form>
            </div>
            <div class="col-md-1">
                <a href="#" class="btn btn-primary hide" id="add-item-attribute-type"><span class="glyphicon glyphicon-edit"></span></a>
            </div>

        </div>
        <div class="row">
            <table class="attributes table table-responseive table-hover">
            <thead>
                <tr>
                    <th>Field Name</th>
                    <th>Type</th>
                    <th class="col-md-1"></th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
        </div>
    </div>
    <div class="tab-pane multi-select" id="locations">
        <form>
            <div class="row">
                <div class="col-md-3">
                    <select class="form-control" id="location-search"></select>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <select class="manage-multiselect form-control input-lg" name="add" multiple></select>
                </div>
                <div class="col-md-2">
                    <div class="row text-center">
                        <a href="#" data-toggle="add" class="btn btn-success modify-location" >Add &gt;&gt;</a>
                    </div>
                    <div class="row text-center">
                        <a href="#" data-toggle="delete" class="btn btn-danger modify-location" >&lt;&lt; Delete</a>
                    </div>
                </div>
                <div class="col-md-5">
                    <select class="manage-multiselect form-control input-lg" name="delete" multiple></select>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="modal fade" role="dialog" id="item-type-form">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="name">Name</label>
                        <div class="controls col-lg-6">
                            <input type="hidden" name="itemTypeId" />
                            <input type="text" class="form-control" name="name" placeholder="Name" />
                            <p class="help-block"></p>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">Cancel</a>
                <a href="#" class="hide btn btn-danger" data-dismiss="modal" id="delete-item-type" aria-hidden="true">Delete</a>
                <a href="#" class="btn btn-primary" id="submit-item-type-form">Save</a>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" role="dialog" id="item-attribute-type-form">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="name">Name</label>
                        <div class="controls col-lg-6">
                            <input type="hidden" name="itemTypeAttributeId" />
                            <select class="form-control" name="itemAttributeTypeId"></select>
                            <p class="help-block"></p>
                        </div>
                    </div>
                </form>
                <form class="form-horizontal" id="attribute-form">

                </form>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">Cancel</a>
                <a href="#" class="hide btn btn-danger" data-dismiss="modal" id="delete-item-type-attribute" aria-hidden="true">Delete</a>
                <a href="#" class="btn btn-primary" id="submit-item-type-attribute-form">Save</a>
            </div>
        </div>
    </div>
</div>