<?= $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="favicon.ico" />
        <title>Inventory Tracker</title>
        <link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/css/bootstrap-responsive.min.css" rel="stylesheet">
        <link href="/css/site.css" rel="stylesheet" media="screen">
		<link href="/css/default/auth.css" rel="stylesheet" media="screen">
    </head>
    <body>
		<?= $this->layout()->content; ?>
    </body>
</html>