<?= $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="favicon.ico" />
        <title>Inventory Tracker</title>
        <link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/css/bootstrap-responsive.min.css" rel="stylesheet">
		<link href="/css/default/index.css" rel="stylesheet" media="screen">
    </head>
    <body>
		<?= $this->layout()->content; ?>
        <?php echo $this->partial('partials/footer.phtml', 'default'); ?>
   		<script src="/js/jquery-2.0.3.min.js" type="text/javascript"></script>
    	<script src="/js/bootstrap.min.js" type="text/javascript"></script>
    	<?= $this->headScript() ?>
    </body>
</html>