<?= $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="favicon.ico" />
        <title>Inventory Tracker</title>
        <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/css/site.css" rel="stylesheet" media="screen">
        <link href="/css/admin/admin.css" rel="stylesheet" media="screen">
    </head>
    <?php echo $this->partial('partials/body.phtml', 'default'); ?>
        <div id="wrap">
            <?php echo $this->partial('partials/menu.phtml', 'default'); ?>
            <div class="container">
                <?= $this->layout()->content; ?>
            </div>
        </div>
        <?php echo $this->partial('partials/footer.phtml', 'default'); ?>
        <script src="/js/jquery-2.0.3.min.js" type="text/javascript"></script>
        <script src="/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/js/jquery.validate.min.js" type="text/javascript"></script>
        <script src="/js/site.js" type="text/javascript"></script>
        <?= $this->headScript() ?>
    </body>
</html>