<?php $url = sprintf('/%s/%s/%s',
        Zend_Controller_Front::getInstance()->getRequest()->getModuleName(),
        Zend_Controller_Front::getInstance()->getRequest()->getControllerName(),
        Zend_Controller_Front::getInstance()->getRequest()->getActionName()
      ); ?>
<div class="navbar">
<div class="navbar-inner">
<div class="container">
<ul class="nav">
<?php if(Zend_Registry::get(SESSION)->userTypeId == Model_User::USER_TYPE_ADMIN) { ?>
    <li <?= $url=='/admin/location/index'?'class="active"':''; ?>><a href="/admin/location/index">Locations</a></li>
	<li <?= $url=='/admin/user/view-employee'||$url=='/admin/user/edit-employee'||$url=='/admin/user/edit-employee-locations'?'class="active"':''; ?>><a href="/admin/user/view-employee">Employees</a></li>
	<li <?= $url=='/admin/user/view-customer'||$url=='/admin/user/edit-customer'||$url=='/admin/user/edit-customer-locations'?'class="active"':''; ?>><a href="/admin/user/view-customer">Customers</a></li>
	<li <?= $url=='/admin/unit/view-unit'||$url=='/admin/unit/edit-unit'||$url=='/admin/unit/edit-unit-users'?'class="active"':''; ?>><a href="/admin/unit/view-unit">Units</a></li>
<?php } else if(Zend_Registry::get(SESSION)->userTypeId == Model_User::USER_TYPE_EMPLOYEE) { ?>
	<li <?= $url=='/admin/user/view-customer'||$url=='/admin/user/edit-customer'||$url=='/admin/user/edit-customer-locations'?'class="active"':''; ?>><a href="/admin/user/view-customer">Customers</a></li>
	<li <?= $url=='/admin/unit/view-unit'||$url=='/admin/unit/edit-unit'||$url=='/admin/unit/edit-unit-users'?'class="active"':''; ?>><a href="/admin/unit/view-unit">Units</a></li>
<?php } ?>
</ul>
</div>
</div>
</div><!-- /.navbar -->
