<?php $url = sprintf('/%s/%s/%s',
    Zend_Controller_Front::getInstance()->getRequest()->getModuleName(),
    Zend_Controller_Front::getInstance()->getRequest()->getControllerName(),
    Zend_Controller_Front::getInstance()->getRequest()->getActionName()
); ?>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">MyStoragePal.com</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <?php if(Zend_Registry::get(SESSION)->userTypeId == Model_User::USER_TYPE_ADMIN) { ?>
                <li <?= $url=='/admin/location/index'?'class="active"':''; ?>><a href="/admin/location/index">Locations</a></li>
                <li <?= $url=='/admin/user/employee'?'class="active"':''; ?>><a href="/admin/user/employee">Employees</a></li>
                <li <?= $url=='/admin/user/customer'?'class="active"':''; ?>><a href="/admin/user/customer">Customers</a></li>
                <li <?= $url=='/admin/unit/index'?'class="active"':''; ?>><a href="/admin/unit/index">Units</a></li>
                <li <?= $url=='/admin/item/index'?'class="active"':''; ?>><a href="/admin/item/index">Items</a></li>
                <?php } else if(Zend_Registry::get(SESSION)->userTypeId == Model_User::USER_TYPE_EMPLOYEE) { ?>
                <li <?= $url=='/admin/user/customer'?'class="active"':''; ?>><a href="/admin/user/customer">Customers</a></li>
                <li <?= $url=='/admin/unit/index'?'class="active"':''; ?>><a href="/admin/unit/index">Units</a></li>
                <?php } ?>
                <li class="dropdown" id="modules-dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown">Modules<b class="caret"></b></a>
                    <div class="dropdown-menu module-dropdown">
                        <form>
                            <div class="form-group">
                                <select class="form-control" name="location">
                                    <option>Select a location</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <select class="form-control" name="module" disabled="disabled">
                                    <option>Select a module</option>
                                </select>
                            </div>
                        </form>
                    </div>
                </li>
                <li><a href="/auth/logout">Logout</a></li>
            </ul>
        </div>
    </div>
</div>
