<div class="row">
	<div class="col-md-4">
		<ul class="nav nav-pills" id="unit-tabs">
  			<li class="active"><a href="#manage">Manage</a></li>
  			<li><a href="#locations" id="customer-units-tab">Customer Units</a></li>
		</ul>
	</div>
	<div class="col-md-8 filters">
    	<a href="#" class="btn btn-primary pull-right" id="add-unit"><span class="glyphicon glyphicon-plus"></span></a>
        <button type="button" class="btn btn-default pull-right" data-toggle="button" id="active-user">Show: Active</button>
        <form class="pull-right">
            <select class="form-control" id="filter-locations"></select>
        </form>
	</div>
</div>
<div class="tab-content">
	<div class="tab-pane active" id="manage">
        <br />
        <table class="units table table-responseive table-hover">
        	<thead>
        		<tr>
        			<th>Name</th>
        			<th>Active</th>
        		</tr>
        	</thead>
        	<tbody>
        	
        	</tbody>
        </table>
	</div>
	<div class="tab-pane" id="locations">
		<form>
			<div class="row">
                <div class="col-md-3 pull-right">
                    <select class="form-control" id="unit-search"></select>
                </div>
				<div class="pull-right">     		
        			<a href="#" class="btn btn-primary" id="assign-customer"><span class="glyphicon glyphicon-user"></span></a>
        		</div>
			</div>
			<div class="row-fluid">
				<table class="users table table-responsive table-hover">
                	<thead>
                		<tr>
                			<th>First Name</th>
                			<th>Last Name</th>
                			<th>Email</th>
                			<th>Current Occupant</th>
                		</tr>
                	</thead>
                	<tbody>
                	
                	</tbody>
                </table>
			</div>
		</form>
	</div>
</div>
<div class="modal fade" role="dialog" id="unit-form">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="name">Name</label>
                        <div class="controls col-lg-6">
                            <input type="hidden" name="unitId" />
                            <input type="hidden" name="locationId" />
                            <input type="text" class="form-control" name="name" placeholder="Name" />
                            <p class="help-block"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="active">Active</label>
                        <div class="controls col-lg-6">
                            <select name="active" class="form-control" >
                                <option value="">Select a value</option>
                                <option value="true">Yes</option>
                                <option value="false">No</option>
                            </select>
                            <p class="help-block"></p>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">Cancel</a>
                <a href="#" class="btn btn-primary" id="submit-form">Save</a>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" role="dialog" id="assign-form">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="userId">Customer</label>
                        <div class="controls col-lg-6">
                            <input type="hidden" name="unitId" />
                            <select class="form-control" name="userId"></select>
                            <p class="help-block"></p>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">Cancel</a>
                <a href="#" class="btn btn-primary" id="submit-assign-form">Save</a>
            </div>
        </div>
    </div>
</div>



