<div class="row-fluid">
	<div class="span6">
		<ul class="nav nav-tabs" id="unit-tabs">
  			<li class="active"><a href="#manage">Manage</a></li>
  			<li><a href="#locations" id="customer-units-tab">Customer Units</a></li>
		</ul>
	</div>
	<div class="span6 filters">
		<div class="pull-right">
			<form>
				<select id="filter-locations"></select>
				<button type="button" class="btn" data-toggle="button" id="active-user">Show: Active</button>
			</form>
			
		</div>
	</div>
</div>

<div class="tab-content">
	<div class="tab-pane active" id="manage">
        <div class="row-fluid">
        	<div class="pull-right">     		
        		<a href="#" class="btn btn-primary" id="add-unit"><i class="icon-home icon-white"></i> +</a>
        	</div>
        </div>
        <br />
        <table class="units table table-hover">
        	<thead>
        		<tr>
        			<th>Name</th>
        			<th>Active</th>
        		</tr>
        	</thead>
        	<tbody>
        	
        	</tbody>
        </table>
	</div>
	<div class="tab-pane" id="locations">
		<form>
			<div class="row-fluid">
				<select id="unit-search"></select>
				<div class="pull-right">     		
        			<a href="#" class="btn btn-primary" id="assign-customer"><i class="icon-user icon-white"></i> +</a>
        		</div>
			</div>
			<div class="row-fluid">
				<table class="users table table-hover">
                	<thead>
                		<tr>
                			<th>First Name</th>
                			<th>Last Name</th>
                			<th>Email</th>
                			<th>Current Occupant</th>
                			<th></th>
                		</tr>
                	</thead>
                	<tbody>
                	
                	</tbody>
                </table>
			</div>
		</form>
	</div>
</div>
<div class="modal hide fade" id="unit-form">
	<div class="modal-header">
    	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    	<h3></h3>
  	</div>
	<div class="modal-body">
    	<form class="form-horizontal">
    		<div class="control-group">
                <label class="control-label" for="inputName">Name</label>
                <div class="controls">
                	<input type="hidden" name="unitId" />
                	<input type="hidden" name="locationId" />
                	<input type="text" name="name" placeholder="Name" />
                	<p class="help-block"></p>
                </div>
  			</div>
  			<div class="control-group">
                <label class="control-label" for="active">Active</label>
                <div class="controls">
                	<select name="active">
                		<option value="">Select a value</option>
                		<option value="true">Yes</option>
                		<option value="false">No</option>
                	</select>
                	<p class="help-block"></p>
                </div>
  			</div>
    	</form>
	</div>
	<div class="modal-footer">
    	<a href="#" class="btn" data-dismiss="modal" aria-hidden="true">Cancel</a>
    	<a href="#" class="btn btn-primary" id="submit-form">Save</a>
	</div>
</div>
<div class="modal hide fade" id="assign-form">
	<div class="modal-header">
    	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    	<h3></h3>
  	</div>
	<div class="modal-body">
    	<form class="form-horizontal">
    		<div class="control-group">
                <label class="control-label" for="inputName">Name</label>
                <div class="controls">
                	<input type="hidden" name="unitId" />
                	<select name="userId"></select>
                	<p class="help-block"></p>
                </div>
  			</div>
    	</form>
	</div>
	<div class="modal-footer">
    	<a href="#" class="btn" data-dismiss="modal" aria-hidden="true">Cancel</a>
    	<a href="#" class="btn btn-primary" id="submit-assign-form">Save</a>
	</div>
</div>