<div class="row">
    <div class="col-md-3">
        <ul class="nav nav-pills" id="location-tabs">
          <li class="active"><a href="#manage">Manage</a></li>
          <li><a href="#modules">Modules</a></li>
        </ul>
    </div>
</div>

<div class="tab-content">
    <div class="tab-pane active" id="manage">
        <div class="row">
            <div class="pull-right">
                <button type="button" class="btn btn-default" data-toggle="button" id="active-location">Show: Active</button>
                <a href="#" class="btn btn-primary" id="add-location"><span class="glyphicon glyphicon-plus"></span></a>
            </div>
        </div>
        <br />
        <table class="locations table table-responseive table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Street</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Zip</th>
                    <th>Phone Number</th>
                    <th>Active</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
    <div class="tab-pane multi-select" id="modules">
        <form>
            <div class="row">
                <div class="col-md-3">
                    <select class="form-control" id="location-search"></select>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <select class="manage-multiselect form-control input-lg" name="add" multiple></select>
                </div>
                <div class="col-md-2">
                    <div class="row text-center">
                        <a href="#" data-toggle="add" class="btn btn-success modify-module" >Add &gt;&gt;</a>
                    </div>
                    <div class="row text-center">
                        <a href="#" data-toggle="delete" class="btn btn-danger modify-module" >&lt;&lt; Delete</a>
                    </div>
                </div>
                <div class="col-md-5">
                    <select class="manage-multiselect form-control input-lg" name="delete" multiple></select>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="modal fade" role="dialog" id="location-form">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="name">Name</label>
                        <div class="controls col-lg-6">
                            <input type="hidden" name="locationId" />
                            <input type="text" class="form-control" name="name" placeholder="Name" />
                            <p class="help-block"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="street">Street</label>
                        <div class="controls col-lg-6">
                            <input type="text" class="form-control" name="street" placeholder="Street" />
                            <p class="help-block"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="city">City</label>
                        <div class="controls col-lg-6">
                            <input type="text" class="form-control" name="city" placeholder="City" />
                            <p class="help-block"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="state">State</label>
                        <div class="controls col-lg-6">
                            <?php echo $this->partial('partials/state-select.phtml', 'default'); ?>
                            <p class="help-block"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="zip">Zip</label>
                        <div class="controls col-lg-6">
                            <input type="text" class="form-control" name="zip" placeholder="Zip Code" />
                            <p class="help-block"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="phoneNumber">Phone Number</label>
                        <div class="controls col-lg-6">
                            <input type="text" class="form-control" name="phoneNumber" placeholder="Phone Number" />
                            <p class="help-block"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="active">Active</label>
                        <div class="controls col-lg-6">
                            <select name="active" class="form-control" >
                                <option value="">Select a value</option>
                                <option value="true">Yes</option>
                                <option value="false">No</option>
                            </select>
                            <p class="help-block"></p>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">Cancel</a>
                <a href="#" class="btn btn-primary" id="submit-form">Save</a>
            </div>
        </div>
    </div>
</div>