<?php $url = sprintf('/%s/%s/%s',
        Zend_Controller_Front::getInstance()->getRequest()->getModuleName(),
        Zend_Controller_Front::getInstance()->getRequest()->getControllerName(),
        Zend_Controller_Front::getInstance()->getRequest()->getActionName()
      ); ?>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">MyStoragePal.com</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li <?= $url=='/default/home/index'?'class="active"':''; ?>><a href="/home">Home</a></li>
                <li <?= $url=='/default/profile/index'?'class="active"':''; ?>><a href="/profile">Settings</a></li>
                <li><a href="/auth/logout">Logout</a></li>
            </ul>

        </div><!--/.nav-collapse -->
    </div>
</div>

