<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">MyStoragePal.com</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li></li>
                <li><a href="/auth/logout">Logout</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <div class="form-group">
                    <a data-toggle="modal" id="change-location" class="btn btn-default" href="#change-location-modal">
                        <span class="location"></span>:
                        <span class="unit"></span>&nbsp;
                        <span class="glyphicon glyphicon-home"></span></a>
                </div>
            </form>
        </div><!--/.nav-collapse -->
    </div>
</div>
<div class="modal fade" id="change-location-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <form role="form" id="location-filters">
                    <div class="form-group">
                        <label for="location">Location</label>
                        <select name="filter-locations" class="form-control input-lg" id="filter-locations"></select>
                    </div>
                    <div class="form-group">
                        <label for="unit">Unit</label>
                        <select name="filter-locations" class="form-control input-lg" id="filter-units"></select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>
