<div class="panel panel-default">
    <div class="panel-heading">Reset Password</div>
    <div class="panel-body">
        <form id="password-form" class="form-horizontal" role="form">
            <div class="form-group">
                <label for="currentPassword" class="col-sm-2 control-label">Current Password</label>
                <div class="col-sm-10">
                    <input type="password" name="currentPassword" autocomplete="off" class="form-control" placeholder="Current Password">
                    <p class="help-block"></p>
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">New Password</label>
                <div class="col-sm-10">
                    <input type="password" name="password" id="password" autocomplete="off" class="form-control" placeholder="New password">
                    <p class="help-block"></p>
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Repeat Password</label>
                <div class="col-sm-10">
                    <input type="password" name="repeatPassword" autocomplete="off" class="form-control" placeholder="Enter new password again">
                    <p class="help-block"></p>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input type="submit" class="btn btn-primary" value="Save">
                    <span id="saved" class="alert alert-success hide">Saved Successfully</span>
                </div>
            </div>
        </form>
    </div>
</div>
